# Generated by Django 5.1.5 on 2025-02-06 18:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsettings',
            options={'verbose_name_plural': 'Account Settings'},
        ),
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'verbose_name_plural': 'Notification Settings'},
        ),
        migrations.AlterModelOptions(
            name='privacysettings',
            options={'verbose_name_plural': 'Privacy Settings'},
        ),
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name_plural': 'Theme Settings'},
        ),
        migrations.RenameField(
            model_name='accountsettings',
            old_name='time_zone',
            new_name='timezone',
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='date_format',
            field=models.CharField(choices=[('YYYY-MM-DD', 'ISO Format'), ('DD/MM/YYYY', 'European Format'), ('MM/DD/YYYY', 'US Format')], default='YYYY-MM-DD', max_length=20),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='system_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='allow_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themesettings',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='layout',
            field=models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('grid', 'Grid')], default='comfortable', max_length=15),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='reduced_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notification_frequency',
            field=models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
